#@TYPE: Machine
#@NAME: intel-skylake-64-multiboot

#@DESCRIPTION: Machine configuration for 64 bit Intel Skylake CPU (and later) with MMX, SSE, SSE2, SSE3, SSE4.1, SSE4.2, AVX, and AVX2 instruction set support. Supports a moderately wide range of drivers that should boot and be usable on "typical" hardware.

# -----------------------------------------------
# Customization of the intel-skylake-64 machine configuration
# -----------------------------------------------

require conf/machine/intel-skylake-64.conf
MACHINEOVERRIDES =. "intel-skylake-64:"

# -----------------------------------------------
# Machine specific configuration
# -----------------------------------------------

DISTRO_FEATURES:append = " systemd"
VIRTUAL-RUNTIME_init_manager = "systemd"
DISTRO_FEATURES_BACKFILL_CONSIDERED = "sysvinit"
VIRTUAL-RUNTIME_initscripts = ""

# Memory and partition table properties
STORAGE_TYPE = "sda"
PTABLE_TYPE = "gpt"

# Bootloader settings
PREFERRED_PROVIDER_virtual/bootloader = "grub"
PREFERRED_RPROVIDER_virtual-grub-bootconf = "rauc-n100-grubconf"

IMAGE_BOOT_FILES = "bzImage efi-boot.vfat grub.cfg grubenv"

# -----------------------------------------------
# Multiboot partition scheme variable definitions
# -----------------------------------------------

WIC_DEVICE="sda"

# Bootloader
WIC_BOOTLOADER_PART_SIZE = "64M"
WIC_BOOTLOADER_PART_CMD = "\
    /boot   --source rawcopy --sourceparams='file=efi-boot.vfat' \
--fstype=vfat --label boot --active --align 4096 --fixed-size ${WIC_BOOTLOADER_PART_SIZE}\
"
WIC_BOOTLOADER_EXTRA_ENV_PART_SIZE = "64M"
WIC_BOOTLOADER_EXTRA_PART_CMD = "part --align 4096 --ondisk sda --no-table --fixed-size ${WIC_BOOTLOADER_EXTRA_ENV_PART_SIZE}"
WIC_BOOTLOADER_ENV_PART_SIZE = "4M"
WIC_BOOTLOADER_ENV_PART_CMD = "\
part --source rawcopy --sourceparams='file=grubenv.vfat' \
--fstype=vfat --label grubenv --align 1024 --fixed-size ${WIC_BOOTLOADER_ENV_PART_SIZE}\
"
WIC_BOOTLOADER_CONFIG = "--ptable ${PTABLE_TYPE}"

# Software partitions
WIC_FIRST_PARTITION_OFFSET = "" 
WIC_KERNELIMG_PART_SIZE = "128M"
WIC_KERNELIMG_SOURCE = "--source bootimg-partition"
WIC_RECOVERY_ROOTFS_PART_SIZE = "768M"
WIC_RECOVERY_ROOTFS_SOURCE = "--source rootfs --rootfs-dir ${RECOVERY_IMAGE_NAME}"
WIC_SYSTEM_ROOTFS_PART_SIZE = "1536M"
WIC_SYSTEM_ROOTFS_SOURCE = "--source rootfs --rootfs-dir ${SYSTEM_IMAGE_NAME}"
WIC_APPFS_MIN_PART_SIZE = "128M"
