# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-intel-multiboot-update"
BBFILE_PATTERN_meta-intel-multiboot-update = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-intel-multiboot-update = "10"

LAYERDEPENDS_meta-intel-multiboot-update = "core intel meta-multiboot-update"
LAYERVERSION_meta-intel-multiboot-update = "2"
LAYERSERIES_COMPAT_meta-intel-multiboot-update = "kirkstone scarthgap styhead"
